"""add_description_to_slot

Revision ID: c9bb82321de7
Revises: 4b5120e617e7
Create Date: 2025-10-07 15:43:53.636102

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c9bb82321de7'
down_revision: Union[str, Sequence[str], None] = '4b5120e617e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('slot', sa.Column('description', sa.Text(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('slot', 'description')
    # ### end Alembic commands ###
