FROM python:3.12-slim
WORKDIR /app

COPY ./pyproject.toml ./poetry.lock ./

RUN pip install poetry && \
    poetry config virtualenvs.create false && \
    poetry install --no-interaction --no-ansi --no-root

COPY ./celery_app /app/celery_app
COPY ./app/core /app/app/core
